version: '3.7'
services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - 3307:3307
    environment:
        MYSQL_DATABASE: myDatabase
        MYSQL_USER: user
        MYSQL_PASSWORD: 12345678
        MYSQL_ROOT_PASSWORD: 12345678
        MYSQL_TCP_PORT: 3307
    expose:
      - 3307
    networks:
      - mynetwork
  app:
    build: 
      context: .
      dockerfile: dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3307/myDatabase?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: 12345678
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge