version: '3.7'
services:
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - 3307:3307
    environment:
      MYSQL_DATABASE: myDatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: 12345678
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_TCP_PORT: 3307
    expose:
      - 3307
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:80
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3307/myDatabase?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345678